bundle:
	mvn clean package

run:
	java -jar target/mcp_document_processing-1.0-SNAPSHOT.jar 

mcp-inspector:
	npx @modelcontextprotocol/inspector java -jar target/mcp_document_processing-1.0-SNAPSHOT.jar