bundle:
	mvn clean package

run:
	java -jar target/mcp_document_processing-1.0-SNAPSHOT.jar 

mcp-inspector:
	npx --yes --package=@modelcontextprotocol/inspector mcp-inspector java -jar target/mcp_document_processing-1.0-SNAPSHOT.jar